### ISSUE TITLE
Vibrant.rgbToHsl is not a function

### ISSUE THREAD

**Issue by nitriques** [akfish/node-vibrant#1]
Looks like the refactoring caused a bug.

I can't create a PR since the build would not work on my machine, but here's how to fix it.

After this line https://github.com/akfish/node-vibrant/blob/master/src/Vibrant.coffee#L14 add

```coffee
util = require('./util')
```

Change the `Vibrant. hslToRgb ` call to `util. hslToRgb` on those two lines

https://github.com/akfish/node-vibrant/blob/master/src/Vibrant.coffee#L122

https://github.com/akfish/node-vibrant/blob/master/src/Vibrant.coffee#L130

**Comment by akfish** [comment]
Oops. I'll fix it right away.

**Comment by akfish** [comment]
Published as 1.0.4

**Comment by nitriques** [comment]
Thanks! Is it on npm as well ?

**Comment by akfish** [comment]
Yep.

**Comment by nitriques** [comment]
Thanks a lot!

**Comment by akfish** [comment]
No problem. :)
