### ISSUE TITLE
Update API to match latest Palette in Android M

### ISSUE THREAD

**Issue by rayshan** [akfish/node-vibrant#10]
Hi, would you please consider this? The latest is supposed to be up to 6x faster and include new APIs such as filters. Here's a video from Google I/O: https://youtu.be/8UicJ0SxBwA?t=19m44s

I believe the latest code is here: https://github.com/android/platform_frameworks_support/blob/master/v7/palette/src/main/java/android/support/v7/graphics/Palette.java

Latest API docs: https://developer.android.com/reference/android/support/v7/graphics/Palette.html

**Comment by akfish** [comment]
Sure. I'll give it some look and get back to you.

**Comment by akfish** [comment]
This issue will track the API changes:
- [ ] `Builder`
- [ ] `Generator`
- [ ] `Filter`

For optimizations, refer to #11 #12.

**Comment by rayshan** [comment]
非常感谢！Sorry I'm not familiar with the algorithms, but let me know how else I can help.

**Comment by akfish** [comment]
Published as 2.0.0.

**Comment by rayshan** [comment]
:tada: 

Tested, it works well, definitely faster. Still need to try some of the advanced features. Thanks!
