### ISSUE TITLE
different results on mobile

### ISSUE THREAD

**Issue by gabrielenosso** [akfish/node-vibrant#103]
Why the examples in the demo page give different results on desktop and mobile?

https://jariz.github.io/vibrant.js/

You can try it out also with the Chrome Dev Tools, just make the Viewport with width less than 1200.

**Comment by crutchcorn** [comment]
VibrantJS is not node-vibrant. node-vibrant is a fork and continuation off of VibrantJS and as a result tests would need to be done with this library itself
