### ISSUE TITLE
Access to Swatch class

### ISSUE THREAD

**Issue by calebjclark** [akfish/node-vibrant#104]
The documentation makes it seem that Swatch is attached to the top-level Vibrant object (Vibrant.Swatch), but it's not. I'd like to use the getBodyTextColor for an existing color I already have. Cool if I submit a pull request with Swatch attached to Vibrant?

**Comment by crutchcorn** [comment]
Please feel free to! I appreciate both the offer to help and making an issue to do so :)

**Comment by calebjclark** [comment]
Thanks for your fast response! Pull request submitted.

**Comment by crutchcorn** [comment]
Linked PR for reference: #105
