### ISSUE TITLE
crossOrigin header makes Chrome bypass it's cache

### ISSUE THREAD

**Issue by jampy** [akfish/node-vibrant#19]
1926a9cc3bce815daa747d43a06713d75e71a451 adds a `crossOrigin` header to *any* request, even if the URL is loaded from the same origin.

This has a negative impact in (at least) Chrome 47:

- say you have image X already loaded in the page (via `new Image()` or classic `<img>`). Chrome will use a copy from it's cache, if available.
- Run Vibrant against image X. Chrome will start a new HTTP request (including `Origin:` header) to load the same image. Cache is effectively disabled in any case - even if the image had already been processed by Vibrant in an earlier request.
- say you load image X again via `new Image()` or `<img>` in the same page (no reload). Chrome will start a third(!) request, even if this one is essentially identical to the first

So, it's (fully) loading an image twice, that would already be present in cache.

Removing the `crossOrigin` header makes Chrome load the image only once - and if possible from cache.

So, please add `crossOrigin` only for requests that are really cross-origin.

**Comment by akfish** [comment]
Fixed in 2.0.2
