### ISSUE TITLE
Support web workers?

### ISSUE THREAD

**Issue by homerjam** [akfish/node-vibrant#25]
Hi,

I'm kind of new to web workers so forgive my lack of knowledge - can this be made to work with them?

Perhaps it would need a new `Image` class - one that takes the input of `canvas.toDataURL()`?

Thanks
James

**Comment by akfish** [comment]
This is certainly doable.
Only `ImageData.data` is passed to `Quantizer` and it can be cloned to web worker. And `Quantizer`&`Generator` should run in web worker context without any issue.
