### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by akfish** [akfish/node-vibrant#26]

**Comment by graingert** [comment]
you can automatically port the coffeescript to https://github.com/decaffeinate/decaffeinate

**Comment by akfish** [comment]
Thanks for the information. 
The TS version has been completed a few months ago. Since no bugs are discovered during the port, I see no reason to publish a version with identical features to the current one.

**Comment by graingert** [comment]
@akfish I can't actually find it.

**Comment by akfish** [comment]
@graingert It's not pushed to GitHub yet. Sorry for the confusion.

**Comment by graingert** [comment]
can you push your TS version?

**Comment by akfish** [comment]
@graingert Sure. I'll push it this weekend, after updating to latest dependencies and fixing a few newly reported bugs.

**Comment by graingert** [comment]
@akfish why don't you push it ASAP, to a non master branch? I'd rather the code wasn't lost if it's only on a handful of machines.
