### ISSUE TITLE
ionic 2

### ISSUE THREAD

**Issue by PierreBresson** [akfish/node-vibrant#30]
Hi,

I'm trying to use node-vibrant with a ionic 2 project but I get an error: 

`"Error in ./ChillPage class ChillPage_Host - inline template:0:0 caused by: __WEBPACK_IMPORTED_MODULE_3_node_vibrant__.Vibrant is not a constructor"`

Here is my code : 

`"import { Vibrant } from 'node-vibrant';"`
...
`"
    let v = new Vibrant('assets/data/artwork.jpg');
"`
`"
    v.getPalette(function(err, palette) {
      if (err) {
          console.log(err);
      }
      else {
          console.log(palette);
      }
    });"`

What am I doing wrong?

**Comment by akfish** [comment]
How about:
```js
import * as Vibrant from 'node-vibrant'
```

**Comment by PierreBresson** [comment]
Now it's working :)

Thanks 👍

**Comment by ranjitnadar** [comment]
<img width="364" alt="screen shot 2017-09-28 at 6 58 52 pm" src="https://user-images.githubusercontent.com/3095820/30969378-d688ed82-a47f-11e7-8040-13f8e8827a5a.png">
any solution for this issue
