### ISSUE TITLE
wrong color population?

### ISSUE THREAD

**Issue by ItamarShDev** [akfish/node-vibrant#32]
Some images get somewhat wrong colors.
For example the following image, the most populated color for some reason is blue, even though we can clearly see that brown is the most  dominant color

The color palette i get is:
```
[ {"population" : 12671, "rgb" : [ 33, 108, 147 ]}, 
  {"population" : 11694 ,"rgb" : [ 117, 80, 56 ]}, 
  {"population" : 9527, "rgb" : [ 250, 250, 249 ]}, 
  {"population" : 8312, "rgb" : [ 158, 200, 214 ]}, 
  {"population" : 5161, "rgb" : [ 180, 163, 140]}, 
  {"population" : 2663,"rgb" : [ 52, 31, 35 ]}]
```

Am I missing something?
![image](https://cloud.githubusercontent.com/assets/953371/22104402/9b95552a-de47-11e6-9f76-1400c5ec2ac0.png)

**Comment by crutchcorn** [comment]
Image quantization is a highly subjective and complex task. We're currently fairly confident in our quantization technique, however we're doing work to make replacing this funtionality significantly easier (by providing a drop-in replacement via a plugin [in the `develop` branch). I'll likely be closing this for cleanup, but will do my best to remember to comment on this issue when that branch becomes `master` and documentation is provided for doing so
