### ISSUE TITLE
NodeJS ES6/ES7

### ISSUE THREAD

**Issue by kyranet** [akfish/node-vibrant#33]
The example given for NodeJS is ancient, probably ES5, and it doesn't work for me.

I'm currently stuck with the following code:

`Vibrant = require('node-vibrant');
Vibrant.from('https://cdn.discordapp.com/icons/256566731684839428/06d25eba0b3b4de642dd3ad82a58bb75.jpg').getSwatches()`

But I get `JimpImage {}` with no properties inside.
All I want is getting the vibrant colour.

I also tried with:
`const Vibrant = require('node-vibrant');
const vibrant = new Vibrant('https://cdn.discordapp.com/icons/256566731684839428/06d25eba0b3b4de642dd3ad82a58bb75.jpg');
vibrant.swatches();`

And got `{ Vibrant: {},
Muted: {},
DarkVibrant: {},
DarkMuted: {},
LightVibrant: {},
LightMuted: {} }`

But they are empty.

**Comment by akfish** [comment]
```js
import * as Vibrant from 'node-vibrant'
```
