### ISSUE TITLE
Take over the original Vibrant.js project?

### ISSUE THREAD

**Issue by jariz** [akfish/node-vibrant#42]
Hey, as there's no way to contact you @akfish (I can't find your email address), I figured I'd just file a issue here.  
Your version of vibrant is obviously superior to the original, so I wondered if you'd be interested in taking over the project and maintaining it.  

You can either take over the repo as it is (I'd add you as a maintainer and you'd redirect from node-vibrant to my repo or something), or I could just add a large warning that I'm abandoning it and people should use yours instead, your call.

Hope you will consider it! I still have a lot of people filing issues in mine, but I just can't be bothered, knowing your far better version exists (which is why I'm abandoning mine).

**Comment by akfish** [comment]
@jariz and I just discussed this over email. We decided to deprecate vibrant.js. Future development and maintenance will be happening. 
I'll keep this great project started by @jariz alive.😀
