### ISSUE TITLE
Angular 4+

### ISSUE THREAD

**Issue by jafaircl** [akfish/node-vibrant#49]
Just to make sure anyone trying to use this library in Angular can find an answer, you have to add:

```typescript
"allowSyntheticDefaultImports": true,
```

to the tsconfig.json file at the root of your project for this to work:

```typescript
import * as Vibrant from 'node-vibrant'
```

After that, everything works fine. I'm not sure if something can be done with the typings to make this unnecessary or not.

**Comment by ranjitnadar** [comment]
<img width="364" alt="screen shot 2017-09-28 at 6 58 52 pm" src="https://user-images.githubusercontent.com/3095820/30969150-29eca816-a47f-11e7-94f2-0042563edd55.png">
Please help me resolve this issue **resolves to a non-module entity and cannot be imported using this construct.**

**Comment by ryanunc1** [comment]
Did you change the line in your tsconfig file?

**Comment by ranjitnadar** [comment]
![Uploading Screen Shot 2017-09-29 at 1.57.50 AM.png…]()
Update in tsconfig.json still getting same errror.

**Comment by edoardoo** [comment]
Same bug here.

**Comment by jafaircl** [comment]
Not sure. It's an Angular issue though so I'd say bring it up over there.

**Comment by voznik** [comment]
I was able to use Vibrant in my A4 setup
use `import Vibrant = require('node-vibrant');`
to [require modules in Typescript](https://www.typescriptlang.org/docs/handbook/modules.html), in your `tsconfig` you should have
```
...
    "moduleResolution": "node",
    "target": "es5",
    "module": "commonjs",
...
```

**Comment by rojasjandro89** [comment]
Declaring it as a global script in the .angular-cli.json file will allow you to use it later using the "declare var x:any" syntax later. But It doesn't give you @types. It's a shame, I feel blind here!
