### ISSUE TITLE
Support buffer for image argument

### ISSUE THREAD

**Issue by rayshan** [akfish/node-vibrant#6]
Hi, sometimes the image file is already read into a buffer, such as when using node-vibrant as a step of a gulp pipeline. It'll be nice to not have to read the file again.

**Comment by akfish** [comment]
Very good point. Though changing the API is generally not a good idea since it will break all the legacy code. 
Instead in next version I'll add a cache interface that will cache images by their names. One can use the default cache implementation by:
```coffee
opts = 
  # Other opts
  # ...
  # Enable internal cache
  useCache: true
  # Maximum image count in cache 
  cacheCapacity: 100

v = new Vibrant('path/to/image', opts)
```

Or use his/her own cache implementation:
```coffee
class CustomCache extends Vibrant.Cache
  # Implement Vibrant.Cache interface

opts = 
  # Other opts
  # ...
  cache: new CustomCache(cacheOpts)

v = new Vibrant('path/to/image', opts)
```

**Comment by akfish** [comment]
There's also a perhaps hacky alternative if you are in a hurry. 

The `Vibrant` constructor's `imagePath` argument are [passed directly to the abstract `Image` constructor](https://github.com/akfish/node-vibrant/blob/master/src/vibrant.coffee#L53), which is [`NodeImage`](https://github.com/akfish/node-vibrant/blob/master/src/node-image.coffee) in node environment. The `NodeImage` [uses Jimp](https://github.com/akfish/node-vibrant/blob/master/src/node-image.coffee#L6) and Jimp's constructor can also take buffer. 
So something like this should work too:
```coffee
# get buffer somehow
# ...

# Use buffer directly (node.js only)
v = new Vibrant(buffer, opts)
```

See https://www.npmjs.com/package/jimp#working-with-buffers

**Comment by rayshan** [comment]
谢谢 @akfish. I can confirm `new Vibrant(imageBuffer);` works. Shaved a little time on processing a very large set of image files. This is the exact API user would expect, so I think you don't need to change any code, just the documentation, right? I'll leave the issue open for you to decide.

**Comment by akfish** [comment]
No problem. I'll document this behavior first and revisit image caching when I have time. Close for now.
