### ISSUE TITLE
Angular 5 Support

### ISSUE THREAD

**Issue by amirping** [akfish/node-vibrant#62]
Trying to use node-vibrant in ng5 project . so i try to import the npm package with 

> import Vibrant = require('node-vibrant');
//or
> import Vibrant from 'node-vibrant' ;
//or 
> import * as Vibrant from 'node-vibrant/src/vibrant';
//or
> import Vibrant = require('node-vibrant/src/vibrant')

without success . 
the i try to use it like that 

> > <script src="node_modules/node-vibrant/dist/vibrant.js" charset="utf-8"></script>
> > declare var Vibrant :any;
> Vibrant.from('this.toPlayRadio.pic').getPalette(function(err, palette) {
>       console.log(palette);
>     });

but it return an error when use it 

> TypeError: this._canvas is undefined
> Stack trace:
> TypeError: this._canvas is undefined
>     BroswerImage.prototype.remove@http://localhost:8080/node_modules/node-vibrant/dist/vibrant.js:12676:9
>     Vibrant.prototype.getPalette/<@http://localhost:8080/node_modules/node-vibrant/dist/vibrant.js:7103:43
>     finallyHandler@http://localhost:8080/node_modules/node-vibrant/dist/vibrant.js:2593:15
>     tryCatcher@http://localhost:8080/node_modules/node-vibrant/dist/vibrant.js:5910:16
>     [22]</module.exports/Promise.prototype._settlePromiseFromHandler@http://localhost:8080
> ...

and this is my tsconfig.json file 

> "compilerOptions": {
>     "target": "es5",
>     "module": "commonjs",
>     "moduleResolution": "node",
>     "sourceMap": true,
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "removeComments": false,
>     "noImplicitAny": false,
>     "noStrictGenericChecks": true,
>     "skipLibCheck": true,
>     "allowSyntheticDefaultImports": true
>   }

and i use 

> "typescript": "^2.6.2",

so i am wondering how to use node-vibrant with ng5 , and how to correctly import it in ts class

**Comment by orgilor** [comment]
import('node-vibrant').then((vibrant) => {
  //code here
})

**Comment by dguo** [comment]
@amirping, I think the issue is that the library is failing to load the image. In #61, see [this commit](https://github.com/akfish/node-vibrant/pull/61/commits/188eca9b7147ccfb03d43861510c9655c4e4182d).

**Comment by ashecret** [comment]
@amirping 

I have managed to use it as below-

`const vibrant = require('node-vibrant');`

**Comment by crutchcorn** [comment]
Using v`3.1.1`, can we confirm that using `import Vibrant = require('node-vibrant')` works?

**Comment by adhirajsinghchauhan** [comment]
@crutchcorn
Tried both `import Vibrant = require('node-vibrant')` and `const Vibrant = require('node-vibrant')`

The former gives #90. The latter gives #85.

**Comment by crutchcorn** [comment]
Thanks for testing. I'll take a closer look this week
