### ISSUE TITLE
Angular - Typescript support

### ISSUE THREAD

**Issue by rojasjandro89** [akfish/node-vibrant#63]
When I import it into an angular project I get the following:
![capture](https://user-images.githubusercontent.com/17559789/35189222-152b21c0-fe14-11e7-9e52-242ad582deae.PNG)
The only way I've been able to use it is declaring it as a global script and then use the "declare var x:any" syntax. But I can't use their types. Is there any way to import it and have the @types available to use? I'm using Angular 5 with the angular CLI and VS Code as my EDI.

**Comment by ashecret** [comment]
@rojasjandro89 

I have managed to use it as below-

`const vibrant = require('node-vibrant');`

**Comment by AggressivelyMeows** [comment]
error TS2304: Cannot find name 'require'.

**Comment by crutchcorn** [comment]
Does `import Vibrant = require('node-vibrant')` work?

**Comment by alisalama** [comment]
No, none of the above work. Same as error as the OP for that format.

and then 
`const vibrant = require('node-vibrant');` and `import Vibrant = require('node-vibrant')` both give the following...

`Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.`

**Comment by akfish** [comment]
node-vibrant itself is written in TypeScript. This should be a TypeScript configuration problem.
The thing is that node-vibrant is a common js package but your TypeScript project is configured to target es modules.

If you search the error message, you should find suitable ways to fix your `tsconfig.json` accordingly. 
For exampe, see Microsoft/TypeScript##22321.
