### ISSUE TITLE
Error upon inculding the vibrant.min.js file in my project

### ISSUE THREAD

**Issue by Quoteme** [akfish/node-vibrant#69]
I get following error:

> Uncaught ReferenceError: Invalid left-hand side expression in prefix operation　　　_vibrant.min.js:1_ 

in my browser, upon using following code:
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>DEMO</title>
        <script src="vibrant.min.js"></script>
    </head>
    <body>
    </body>
</html>
```

this is my operating system + browser I used:

> Chromium | 65.0.3325.181 (Offizieller Build) Arch Linux (64-Bit)

**Comment by vasildev** [comment]
+1

**Comment by christophwolff** [comment]
+1

**Comment by Quoteme** [comment]
I found a fix:
use the Vibrant.min.js file used on the demo page > [https://jariz.github.io/vibrant.js/](https://jariz.github.io/vibrant.js/)
the direct link to this working version of Vibrant.min.js is: [https://jariz.github.io/vibrant.js/dist/Vibrant.min.js](https://jariz.github.io/vibrant.js/dist/Vibrant.min.js)
