### ISSUE TITLE
A wild console.log appears

### ISSUE THREAD

**Issue by gpbmike** [akfish/node-vibrant#7]
Noticed this spitting out image dimensions in my console. Intentional?

https://github.com/akfish/node-vibrant/blob/master/src/browser-image.coffee#L25

```coffee
console.log @width, @height
```

Also, awesome tool. Checking it out for the first time today. :+1:

**Comment by akfish** [comment]
Thanks for pointing it out. It's just some debug code being left over. I'll clean it up.
