### ISSUE TITLE
Unhandled promise rejection EVEN IF there is catch

### ISSUE THREAD

**Issue by zhangciwu** [akfish/node-vibrant#72]
```
var Vibrant = require('node-vibrant');

try{
Vibrant.from('http://img.ucweb.com/s/mediana/s/yoda_xiss/1805081022849d64044d7d2953bc494b804ce7b7a1x251x120x547.gif')
    .getPalette()
    .then((palette) => {

    })
    .catch((error)=>{
        console.log('error',error);
    })

}catch (e) {
    console.log('error',e);
}

```

Just can not catch the exception.
The two catches are not working,
just got `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Unknown graphic control label: 0x2a`

**Comment by crutchcorn** [comment]
Can this be retested against `3.1` release?

**Comment by zhangciwu** [comment]
Tested with 3.1.0 and 3.1.1,
Now correctly catch by provided catcher.
