### ISSUE TITLE
Is it possible to use the same color palette on different images?

### ISSUE THREAD

**Issue by mertyildiran** [akfish/node-vibrant#83]
I have two nearly identical images and I want to use the same color palette generated from the first image on the second image. Therefore I will find the similarity rate of these two images. So is it possible to use the same color palette on different images?

**Comment by crutchcorn** [comment]
Not to sound like a canned message, but similar to #88:

I think this is out-of-scope for current work, as we're focusing on getting image extraction working (and this library does currently not include logic for ~complimentary colors/etc~ comparing two color differences AFAIK). However, we're doing a lot of work in the `develop` branch to make many packages where this might fit in better (and in the case to this issue, our modularity system might be a great help as a drop-in for the image quantizer would likely help a lot). I'll mark as question and we'll revisit and development goes on
