### ISSUE TITLE
Use rgb or # string as input instead of image

### ISSUE THREAD

**Issue by madprops** [akfish/node-vibrant#88]
Right now I'm looking for something to generate a palette with some contrasting colors, specifically different colors, not the same color darker or brighter. Thought this could help but I don't see an option to use a color as input instead of an image.

**Comment by crutchcorn** [comment]
I think this is out-of-scope for current work, as we're focusing on getting image extraction working (and this library does currently not include logic for complimentary colors/etc AFAIK). However, we're doing a lot of work in the `develop` branch to make many packages where this might fit in better. I'll mark as question and we'll revisit and development goes on
