### ISSUE TITLE
ERROR: this.opts.ImageClass is not a constructor when calling getPalette()

### ISSUE THREAD

**Issue by adhirajsinghchauhan** [akfish/node-vibrant#90]
Angular v7.2.4
node-vibrant v3.2.0-alpha

This is the error:
> ERROR TypeError: this.opts.ImageClass is not a constructor
    at Vibrant.push../node_modules/@vibrant/core/lib/index.js.Vibrant.getPalette (index.js:42)
    at Builder.push../node_modules/@vibrant/core/lib/builder.js.Builder.getPalette (builder.js:62)

Code used:
```
import Vibrant from '@vibrant/core';
// or: import Vibrant from 'node-vibrant/lib/config', doesn't matter

// Supplying an image URL
// Tried passing an HTMLImageElement as well, same error.
Vibrant.from('https://example.com/image.png')
  .getPalette((error, palette) => {});
```

tsconfig.json:
```
{
  "compilerOptions": {
    // other configs
    "module": "commonjs",
    "allowSyntheticDefaultImports": true,
    "allowJs": true
  }
}
```

**Comment by adhirajsinghchauhan** [comment]
Bump

**Comment by crutchcorn** [comment]
Use `3.1.2` for now. 3.2 is an alpha and is largely untested and as a result has many known issues associated with it

**Comment by vlow** [comment]
I'm running into the same error with 3.1.5. I'm using Angular 9.

I'm importing vibrant like this `import Vibrant from 'node-vibrant/lib/vibrant';` and I try to use it like that `Vibrant.from(this.shop.imageUrl).getPalette().then((palette) => console.log(palette));`.

**Comment by Scipionh** [comment]
Same issue with the version 3.1.5, Angular 10.

**Comment by Basher7** [comment]
Getting same error with version 3.1.6 in Angular 10

**implement vibrent as bellow**
> import Vibrant from 'node-vibrant/lib/vibrant';

**then in my Code**
```typescript
Vibrant.from(this.DoctorPointLogo).quality(1).clearFilters()
     .maxColorCount(20).getSwatches().then((palette) => {
        /// your code
});
```

**Error stack**

> core.js:4352 ERROR TypeError: this.opts.ImageClass is not a constructor
    at Vibrant.push.aJk8.Vibrant.getPalette (vibrant.js:57)
    at Builder.push.TZCp.Builder.getSwatches (builder.js:60)

**Comment by Basher7** [comment]
@Scipionh with version 3.1.5 in Angular 10 change node-vibrent import as below

replace this `import Vibrant from 'node-vibrant/lib/vibrant';` by `var Vibrant = require('node-vibrant');`
In my project problem fixed after this changes.

**Comment by danbulant** [comment]
> Use `3.1.2` for now. 3.2 is an alpha and is largely untested and as a result has many known issues associated with it

3.2 is still alpha. Why is it released on npm/set as the latest version? This error still happens when using getPallete on node.
