### ISSUE TITLE
Readme: Describe output of this library

### ISSUE THREAD

**Issue by danielberndt** [akfish/node-vibrant#91]
Hi there,

I'm planning on trying out this library and by judging from Readme it all seems well thought out and quite promising.

Interestingly, it misses to describe the shape of the output though!
All I've learned ist that I'll get a `Palette`. It presumably contains `Swatches`. But it's not really clear what this means before being able to try it out on some real examples.

**Comment by crutchcorn** [comment]
We're currently working on hugely increased docs for the develop branch with a monorepo rewrite.

**Comment by danielberndt** [comment]
Ah that's great to know!

**Comment by polarathene** [comment]
Did those docs ever materialize? The `develop` branch for monorepo has a README that just leaves the section as TODO.

Looks like a good project, with an API that's been thought out, but without some better documentation I feel it's affecting adoption a bit?

I had come here from the archived `vibrant.js` repo after viewing their demo page, but while the `master` branch README lists a bunch of interesting APIs, there seems to lack any mention of what sort of results to expect, doesn't appear to be anything about the vibrant/muted types and variants or similar? 

I could install the package and try find out what sort of output is provided, but definitely useful to include in the README. Seems like development has stalled (which is fine, I understand how that is), so if completing the mono repo transition is not likely to happen soon, perhaps a small update to README on `master` would be good?
