### ISSUE TITLE
Node.js Results Different than Browser?

### ISSUE THREAD

**Issue by richdunajewski** [akfish/node-vibrant#95]
I'm using the library under Node.js and I do get the swatches back from `getPalette()`, but the result returns undefined for `getTitleTextColor()` and `getBodyTextColor()` methods. If I use the same image and call from the browser, these methods exist and return a hex value.

I know there are differences in the values returned in each environment, but shouldn't the color methods above work on Node.js as well? The use case is to determine which colors can be overlaid onto the image to generate a new image with a text caption in Node.

**Comment by crutchcorn** [comment]
You're totally right. I've found the edgecase where there was an incorrectly typed conditional. Should be fixed in 3.1.2
