### ISSUE TITLE
Node.js - Crash when pulling image over broken SSL

### ISSUE THREAD

**Issue by theninj4** [akfish/node-vibrant#98]
Hey :wave: I've found a bug, specifically here:
https://github.com/akfish/node-vibrant/blob/master/src/image/node.ts#L27-L32

```javascript
      handler.get(src, (r: any) => {
        let buf = Buffer.alloc(0)
        r.on('data', (data: any) => { buf = Buffer.concat([buf, data]) })
        r.on('end', () => resolve(buf))
        r.on('error', (e: Error) => reject(e))
      })
```

Basically when downloading an image from a host whereby the SSL certificate is invalid in some way the core `https.get()` function will reject. It's not an incredibly obvious rejection, but you can see it here in their docs: https://nodejs.org/api/https.html#https_https_get_url_options_callback
```javascript
const https = require('https');

https.get('https://encrypted.google.com/', (res) => {
  ...
}).on('error', (e) => {
  console.error(e);
});
```

Locally I've been replacing the closing brace+bracket for `}).on('error', (e) => { reject(e); });` to convert the unhandled rejection into something I can catch and handle in my project.

In the `develop` branch it'll likely need tweaking here too: https://github.com/akfish/node-vibrant/blob/develop/packages/vibrant-image-node/src/index.ts#L36-L41 :smiley:

**Comment by crutchcorn** [comment]
Thanks for looking into this and providing such a detailed bug report!

I'm busy for the next week or so, so apologies for the delay in advanced, but I'm trying to put in some more time into node-vibrant recently.

Otherwise, if this is a fix you're hoping for fairly soon, PRs are always welcome, appreciated, and are easier to set time for :)

**Comment by theninj4** [comment]
Awesome. I've put in a PR to fix the bug, along with a second PR to get the build working again following some breaking changes to TravisCI :)

**Comment by crutchcorn** [comment]
You're amazing @theninj4 thank you so so much. I apologize for my delays - always so much going on and have a hard time balancing it all
